<?php 
  $today = date("d-m-y");
   //echo "reviewed on ". $today ;
?>
  <!-- generated by Mainstream::Melody on <?php echo $today; ?> -->
  <!-- <base href="https://www.rulsey.com/" /> -->
  <link rel="dns-prefetch" href="https://rulseyprojects.com" crossorigin="anonymous">
  <link rel="dns-prefetch" href="https://static.rulseyprojects.com" crossorigin="anonymous">
  <meta data-react-helmet="true" http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
	<meta data-react-helmet="true" http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<meta data-react-helmet="true" name="viewport" content="width=device-width, height=device-height, maximum-scale=1.0, initial-scale=1.0, minimum-scale=1.0, user-scalable=no" />
  <meta data-react-helmet="true" name="referrer" content="origin" />
  <meta data-react-helmet="true" name="image" content="/static/ce0b021bf2247d0c0f7c000f788373cd/performance-lc.png" />
  <meta data-react-helmet="true" property="og:image" content="images/letter-r(1).png" />
  <meta data-react-helmet="true" property="og:image" content="images/letter-r(1).png" />
  <meta data-react-helmet="true" property="og:site_name" content="rulsey" />
  <meta data-react-helmet="true" name="robots" content="all" />
  <meta data-react-helmet="true" name="GOOGLEBOT" content="index,follow" />
  <meta data-react-helmet="true" name="yahooBOT" content="index,follow" />
  <meta data-react-helmet="true" name="duckduckbot" content="index,follow" />
  <meta data-react-helmet="true" name="baiduspider" content="index,follow" />
  <meta data-react-helmet="true" name="yandexBOT" content="index,follow" />
  <meta data-react-helmet="true" name="exaBOT" content="index,follow" />
  <meta data-react-helmet="true" name="ia_archiver" content="index,follow" />
  <meta data-react-helmet="true" name="robots" content="noarchive, translate, imageindex" />
  <meta data-react-helmet="true" name="distribution" content="global" />
  <meta data-react-helmet="true" name="rating" content="general" />
  <meta data-react-helmet="true" name="revisit-after" content="1 days" />
  <meta data-react-helmet="true" name="revisit" content="1 days" />
  <meta data-react-helmet="true" content="document" name="resource-type" />
  <meta data-react-helmet="true" content="all" name='audience' />
  <meta data-react-helmet="true" content="en-us" name='language' />
  <meta data-react-helmet="true" name="title" content="A vast network of Love" />
  <meta data-react-helmet="true" http-equiv="Pragma" content="no-cache" />
  <meta data-react-helmet="true" http-equiv="Cache-Control" content="private, no-cache, no-store, must-revalidate, max-age=0, max-stale=0" />
  <meta data-react-helmet="true" name="description" content="Rulsey is a social network that connects you with your interests, friends and loved ones.see what&#039;s happening around you with free messaging and a lot more. Sign up now." />
  <link rel="shortcut icon" href="https://static.rulseyprojects.com/construct/docs/logo.png">
  <link rel="apple-touch-icon" sizes="57x57" href="https://static.rulseyprojects.com/construct/docs/apple-icon-57x57.png" />
  <link rel="apple-touch-icon" sizes="60x60" href="https://static.rulseyprojects.com/construct/docs/apple-icon-60x60.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="https://static.rulseyprojects.com/construct/docs/apple-icon-72x72.png" />
  <link rel="apple-touch-icon" sizes="76x76" href="https://static.rulseyprojects.com/construct/docs/apple-icon-76x76.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="https://static.rulseyprojects.com/construct/docs/apple-icon-114x114.png" />
  <link rel="apple-touch-icon" sizes="144x144" href="https://static.rulseyprojects.com/construct/docs/apple-icon-144x144.png" />
  <link rel="apple-touch-icon" sizes="180x180" href="https://static.rulseyprojects.com/construct/docs/apple-icon-180x180.png" />
  <link rel="icon" type="image/png" sizes="192x192" href="https://static.rulseyprojects.com/construct/docs/android-icon-192x192.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="https://static.rulseyprojects.com/construct/docs/favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="96x96" href="https://static.rulseyprojects.com/construct/docs/favicon-96x96.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="https://static.rulseyprojects.com/construct/docs/favicon-16x16.png" />
  <link rel="stylesheet" type="text/css" href="./assets/css/normalize.css"  crossorigin="anonymous"/>
  <link rel="stylesheet" href="https://unpkg.com/@themesberg/flowbite@1.3.0/dist/flowbite.min.css" crossorigin="anonymous" />
  <link rel="stylesheet" type="text/css" href="./assets/css/stylet.css" crossorigin="anonymous"/>
  <link rel="stylesheet" type="text/css" href="./assets/css/tailwind.output.css"  crossorigin="anonymous"/>
  <link rel="stylesheet" type="text/css" href="./assets/css/styles.css"  crossorigin="anonymous"/>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com"  crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet" />
  
